### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by xaria-coin** [Pennykoin/Pennykoin#1]
Hi

Sorry I had build failed earlier - not at pc at moment to advise of specifics

**Comment by jerrimus** [comment]
Pk is NOT production yet, I am changing many things multiple times a
day.   When it's time for release I will reset the blockchain and post ANN
on bitcointalk/twitter/reddit.

Sorry if I hadn't made that clear, hopefully about a week or so.

**Comment by dahifi** [comment]
@Z3RO-COOL, there shouldn't be any problems now.
