### ISSUE TITLE
CLI: new named wallets saved as .wallet

### ISSUE THREAD

**Issue by dahifi** [Pennykoin/Pennykoin#5]
When creating a new wallet in pkwallet, it saves a .wallet file, no matter what the name selected at creation. 

This causes two problems: one the wallet cannot be opened unless renamed, and additional wallets cannot be created until it has been done.

**Comment by Pennykoin** [comment]
Hey is it possible it wasn't exited properly? I've had this issue when I've ctrl+c out of the cli, but not otherwise

**Comment by dahifi** [comment]
No, I exited properly and have tested multiple times. 

`./pkwallet --generate new wallet test1 --password 1234`

Then exit, try to create another wallet: 

```
./pkwallet --generate new wallet test2 --password 1234 --daemon-host seed2.pennykoin.com 
pennykoin wallet v3.0.0.franken(0.1-g72946d9)
Error: .wallet already exists
Failed to initialize wallet
```

The .wallet and .address files should both have the wallet names in front of them, as evidenced by: 

```
./pkwallet --wallet-file test1
pennykoin wallet v3.0.0.franken(0.1-g72946d9)
password: ****
Error: failed to load wallet: wallet file 'test1.wallet' is not found
Failed to initialize wallet

```

**Comment by dahifi** [comment]
I don't see anything wrong with SimpleWallet.cpp::walletFileName, so I'm thinking it must be in WalletHelper::prepareFileNames. I downloaded a new IDE to try to do some debugging using breakpoints but I'm having some issues with it.

**Comment by Pennykoin** [comment]
pending dahifi patch fixed
